server:
  port: 8181

spring:
  datasource:
    username: root
    password: root
    #url中database为对应的数据库名称
    url: jdbc:mysql://localhost:3308/library?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
#  security:
#    user:
#      name: admin
#      password: admin
#      roles: admin
#  redis:
#    host: 127.0.0.1
#    port: 6379

mybatis-plus:
  mapper-locations: classpath:com/example/demo/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.example.demo.entity
  global-config:
    db-config:
      id-type: auto
  #配置日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#showSql
logging:
  level:
    com.example.demo.mapper: debug
